# -*- coding: utf-8 -*-
"""交付层：按 ARC-Bench 官方契约把生成的应用铺到 output_dir 根。

官方空白模板取证（五连败根因）：平台以 `--output-dir` 本身作为项目根
（"output_dir becomes the project root"）——在根上找应用、按根的启动
契约启动、跑 Playwright。我方管线此前把应用埋在
`output_dir/projects/<dirname>/code/` 两层深处，平台从未见过应用。

交付动作（全部机械、加法式）：
1. 把 code/ 全部内容复制到 output_dir 根（排除 __pycache__）；
2. 静态探测组装模块（create_app 提供者）→ 生成根级 app.py
   （create_app + PORT 环境变量监听）；
3. 生成根级 package.json（"start": "python app.py"）——官方脚手架
   为 Node 系启动约定，npm start 桥接让该约定也能拉起 Python 应用；
4. 重写 template.yaml 为 Python 栈声明。

任何失败都不上抛（交付失败仅记录，主流程与评分照常）。
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path


def _detect_assembly_pkg(code_dir: Path) -> str | None:
    """静态探测 create_app 提供者（最上层的包）。优先含 blueprint 注册
    痕迹（register_blueprint）的包；同分时取名字典序最大（组装模块
    通常最后生成/名字靠后，如 web_ui/webapp/view_mode）。"""
    candidates: list[tuple[str, int]] = []
    for child in sorted(code_dir.iterdir()):
        if (not child.is_dir() or child.name.startswith(("_", "."))
                or child.name == "tests"):
            continue
        score = 0
        has_create = False
        for py in child.rglob("*.py"):
            if "__pycache__" in py.parts:
                continue
            try:
                src = py.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            if "def create_app" in src:
                has_create = True
            if "register_blueprint" in src:
                score += 1
        if has_create:
            candidates.append((child.name, score))
    if not candidates:
        return None
    candidates.sort(key=lambda t: (t[1], t[0]), reverse=True)
    return candidates[0][0]


_APP_PY_TEMPLATE = '''# Auto-generated by token-burner delivery layer.
# Root entrypoint: the platform starts the app per the scaffold contract
# (PORT env; /api/health; app.run under __main__).
import os

from {assembly} import create_app

app = create_app()

if __name__ == "__main__":
    port = int(os.environ.get("PORT", "3301"))
    app.run(host="0.0.0.0", port=port)
'''

_PACKAGE_JSON = {
    "name": "generated-app",
    "version": "1.0.0",
    "private": True,
    "scripts": {
        "start": "python app.py",
    },
}

_TEMPLATE_YAML = '''schema_version: "1.0"
id: web-python-flask
name: Web Application (Python + Flask)
type: web_app
version: 1.0.0
description: Flask application generated by token-burner (delivery layer).
stack:
  backend:
    framework: Flask
    language: Python
    database: SQLite
  tests:
    e2e: Playwright
copy:
  exclude:
    - template.yaml
    - __pycache__
agent_guidance:
  api_root: .
  entrypoint: app.py
'''


def deliver_to_output_root(code_dir: Path, output_dir: Path) -> list[str]:
    """把 code_dir 的内容按官方契约交付到 output_dir 根。

    返回动作记录列表（空列表 = code_dir 不存在）。重复调用安全
    （dirs_exist_ok 覆盖式复制；清单文件幂等重写）。
    """
    code_dir = Path(code_dir)
    output_dir = Path(output_dir)
    if not code_dir.is_dir():
        return []
    actions: list[str] = []

    # 1) 应用内容铺到根
    for source in sorted(code_dir.iterdir()):
        if source.name == "__pycache__":
            continue
        destination = output_dir / source.name
        if source.is_dir():
            shutil.copytree(source, destination, dirs_exist_ok=True,
                            ignore=shutil.ignore_patterns("__pycache__"))
        else:
            shutil.copy2(source, destination)
    actions.append("copied code/* → output root")

    # 2) 组装探测 + 根级 app.py
    if not (output_dir / "app.py").exists():
        assembly = _detect_assembly_pkg(code_dir)
        if assembly:
            (output_dir / "app.py").write_text(
                _APP_PY_TEMPLATE.format(assembly=assembly),
                encoding="utf-8")
            actions.append(f"app.py → create_app@{assembly}")

    # 3) npm start 桥接（官方脚手架为 Node 系启动约定）
    (output_dir / "package.json").write_text(
        json.dumps(_PACKAGE_JSON, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8")
    actions.append("package.json (start=python app.py)")

    # 4) Python 栈声明
    (output_dir / "template.yaml").write_text(
        _TEMPLATE_YAML, encoding="utf-8")
    actions.append("template.yaml → python-flask")

    return actions
